language: node_js
node_js: stable

branches:
  only:
    - master

stages:
  - install_ssh
  - install_package_manage
  - generate_example
    if: type IN (pull_request) AND branch IN (master)

cache:
  directories:
    - node_modules

install_ssh:
  # 配置 ssh key
  - openssl enc -aes-256-cbc -d -K $ssh_key -iv $ssh_iv -in ./travis_ssh.enc -out ~/.ssh/travis_ssh
  - cp -af ./travis_ssh.pub ~/.ssh/travis_ssh.pub
  - cp -af ./ssh.config ~/.ssh/config
  - chmod 600 ~/.ssh/travis_ssh
  - eval $(ssh-agent)

install_package_manage:
    # 安装 yarn、skpm
  - npm install -g yarn
  - yarn global add skpm

# 创建 example
generate_example:
  - rm -rf ./example
  - skpm create example --template=yinxulai/sketch-plugin-template-webview-with-react
  - git status
  - git remote
  - git add ./example
  - git config user.name "travis bot"
  - git commit -m "auto update example"
  - git config user.email "travis@yinxulai.com"
  - git remote set-url origin git@github.com:yinxulai/sketch-plugin-template-webview-with-react.git
  - git push --quiet origin HEAD:master
